apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: front-end.yaml
images:
- name: 947956828554.dkr.ecr.ap-northeast-1.amazonaws.com/front-end-test # 変更箇所
  newTag: "ed71785" # 変更箇所