apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: front-end
  namespace: sock-shop
spec:
  serviceRef:
    name: front-end
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-1:012345678912:targetgroup/eks-example/xxxx #　変更箇所