apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: front-end.yml
images:
  - name: 947956828554.dkr.ecr.ap-northeast-1.amazonaws.com/front-end-test
    newTag: "ed71785"